[package]
name = "lucid"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = {version = "4.0.0", features = ["derive"]}
tracing = "0.1.38"
tracing-subscriber = "0.3.16"
colored = "2.0.0"
ratatui = "0.29.0"
